<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-H3SL47G" name="Default test" tests="5" failures="1" timestamp="21 May 2019 04:46:31 GMT" time="5.38" errors="0">
  <testcase name="getAllPlanets" time="2.675" classname="task.one.SWAPI.Planets.StarWarsAPI"/>
  <testcase name="getPlanetByID_Negative" time="0.828" classname="task.one.SWAPI.Planets.StarWarsAPI">
    <failure type="java.lang.AssertionError" message="Wrong Planet - Test Passed expected [Alderaan] but found [Yavin IV]">
      <![CDATA[java.lang.AssertionError: Wrong Planet - Test Passed expected [Alderaan] but found [Yavin IV]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at task.one.SWAPI.Planets.StarWarsAPI.getPlanetByID_Negative(StarWarsAPI.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getPlanetByID_Negative -->
  <testcase name="getPlanetByID_Positive" time="1.153" classname="task.one.SWAPI.Planets.StarWarsAPI"/>
  <testcase name="getResponseTime" time="0.238" classname="task.one.SWAPI.Planets.StarWarsAPI"/>
  <testcase name="verifyResponseCode" time="0.475" classname="task.one.SWAPI.Planets.StarWarsAPI"/>
</testsuite> <!-- Default test -->
